#!/usr/bin/env perl -s

$w = "1,0.697263,0.396540,2.270819,-0.145200,0.038503,29.518480,-3.411896,-3.732196,0.217455,0.041551,0.060136" unless defined $w;

@W = split(',',$w);
for ($i=0; $i<$#W; $i++) {
    $ZF[$i] = 0.0;
}

while (<>) {
    chomp;
    @L = split(" ", $_);
    $spv = pop @L;
    @VV = split(",",$spv);
    shift @VV;
    $dim = shift @VV;
    @F = @ZF;
    $x = 0.0;
    while (@VV) {
	$i = shift @VV;
	$F[$i-1] = shift @VV;
	$x += $F[$i-1] * $W[$i-1];
    }
    print join(" ", @L)," ||| ", join(" ",@F)," ||| $x\n";
}




